[package]
name = "bls-crypto"
version = "0.3.0"
authors = ["Kobi Gurkan <kobigurk@gmail.com>", "Michael Straka <mstraka@clabs.co>", "Georgios Konstantopoulos <me@gakonst.com>", "Lucas Ege <lucas@clabs.co>", "Victor Graf <victor@clabs.co>"]
edition = "2018"

[dependencies]
ark-bls12-377 = { version = "0.4" }
ark-serialize = { version = "0.4", features = [ "derive" ] }
ark-ff = { version = "0.4", features = [ "std" ] }
ark-ec = { version = "0.4", features = [ "std" ] }
ark-std = { version = "0.4", features = [ "std" ] }
ark-ed-on-bw6-761 = { version = "0.4" }
ark-crypto-primitives = { version = "0.4", features = [ "crh" ]  }

# other deps
rand = "0.8.4"
byteorder = "1.4.3"
hex = "0.4.3"
clap = "4.5.4"
log = "0.4.14"
lru = "0.12.3"
env_logger = "0.10"
blake2s_simd = "1.0.0"
csv = "1.1.6"
rand_chacha = "0.3"
thiserror = "1.0.30"
once_cell = "1.9.0"

[dev-dependencies]
criterion = "0.5.1"
rand_xorshift = "0.3"

[[example]]
name = "simple_signature"
path = "examples/simple_signature.rs"

[[example]]
name = "pop"
path = "examples/pop.rs"

[[example]]
name = "pop_csv"
path = "examples/pop_csv.rs"

[lib]
crate-type = ["lib", "staticlib"]

[features]
default = [ "compat" ]
test-helpers = []
compat = []

# Enable parallel computation. Cannot be used with WASM.
parallel = ["ark-ec/parallel", "ark-ff/parallel", "ark-crypto-primitives/parallel"]

[[bench]]
name = "batch_bls"
harness = false
