name: CI for BLS Crypto Library

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build bls-crypto
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - nightly
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
            toolchain: ${{ matrix.toolchain }}

      - name: Cache
        uses: swatinem/rust-cache@v2

      - name: Build
        run: cargo build

  test:
    name: Test bls-crypto
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - nightly
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
            toolchain: ${{ matrix.toolchain }}

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: cargo test

  examples:
    name: Run examples
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - nightly
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
            toolchain: ${{ matrix.toolchain }}

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run simple_signature example
        run: cargo run --example simple_signature -- -m "dark is the night"
      - name: Run pop example
        run: cargo run --example pop -- -k "23a6427c31fe9eb70ee1cc556835f51e02c6eec7b5ecc5aebaceac494ed8a710"
      - name: Run pop_csv example
        run: cargo run --example pop_csv -- -n 3 -o pop.csv
