name: Run BLS Crypto Library Examples

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  example_simple_signature:
    name: Run simple_signature example
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo run --example simple_signature -- -m "dark is the night"

  example_pop:
    name: Run pop example
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo run --example pop -- -k "23a6427c31fe9eb70ee1cc556835f51e02c6eec7b5ecc5aebaceac494ed8a710"

  example_pop_csv:
    name: Run pop_csv example
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo run --example pop_csv -- -n 3 -o pop.csv
